services:
  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    networks:
      - frontend
      - backend
    depends_on:
      - php
      - mysql

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:
      - ./www:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "6001:80"
  
    networks:
      - backend

networks:
  frontend:
  backend:
